# ------------------------------------------------------------------
# includes
# ------------------------------------------------------------------

include:
  - ".gitlab/ci/backends.yml"
  - ".gitlab/ci/oba-ui.yml"
  - ".gitlab/ci/devportal-ui.yml"
  - ".gitlab/ci/tpp-ui.yml"
  - ".gitlab/ci/pmd.yml"
  - ".gitlab/ci/postman.yml"

# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Code Analysis"         # static code analysis
  - "Code Testing"          # evaluate code and analysis results
  - "Code Compilation"      # build jar and provide as artifact
  - "Unit Testing"          # run tests and code quality checks
  - "Docker Testing"        # test building docker images, on success pass docker image
  - "Docker Publishing"     # push to DockerHub
  - "OpenShift Deployment"  # deploy to OpenShift
  - "Maven Release"         # release to Maven Central

# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables:

  # Sub-directory of Dockerfile
  DOCKER_DIR_ONLINE_BANKING: "online-banking/online-banking-app"
  DOCKER_DIR_CERTIFICATE_GENERATOR: "certificate-generator"
  DOCKER_DIR_POSTMAN_TESTS: "postman-scripts"
  DOCKER_DIR_ONLINE_BANKING_UI: "oba-ui"
  DOCKER_DIR_TPP_UI: "tpp-ui"
  DOCKER_DIR_DEVPORTAL_UI: "developer-portal-ui"

  # Image name on DockerHub and in OpenShift
  DOCKER_IMAGE_ONLINE_BANKING: "xs2a-online-banking"
  DOCKER_IMAGE_CERTIFICATE_GENERATOR: "xs2a-certificate-generator"
  DOCKER_IMAGE_POSTMAN_TESTS: "xs2a-postman-tests"
  DOCKER_IMAGE_ONLINE_BANKING_UI: "xs2a-online-banking-ui"
  DOCKER_IMAGE_TPP_UI: "xs2a-bank-tpp-ui"
  DOCKER_IMAGE_DEVPORTAL_UI: "xs2a-bank-devportal"

  ###########################
  # Public Dockerhub Images #
  ###########################

  DOCKERHUB_REGISTRY: "docker.io"
  DOCKERHUB_NAMESPACE: "adorsys"

  ############################
  # Private Openshift Images #
  ############################

  OPENSHIFT_NAMESPACE_DEV: "adorsys-dynamic-sandbox-dev"
  OPENSHIFT_NAMESPACE_INTEG: "adorsys-dynamic-sandbox-integ"
  OPENSHIFT_NAMESPACE_DEMO: "adorsys-dynamic-sandbox-demo"

  ###########################
  # Build variables         #
  ###########################

  # Defaults for Java 8
  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

.build_java:
  image: "adorsys/ci-build"
  script:
    - jabba use $BUILD_JAVA_VERSION
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -DskipTests clean install
  cache:
    key: "Java_${CI_COMMIT_REF_SLUG}"
    paths:
    - /builds/adorsys/xs2a/psd2-dynamic-sandbox/.m2/repository

# args:
#   ${DOCKER_DIR}
#   ${DOCKER_IMAGE}
.build_dockerimage:
  image: "adorsys/ci-build"
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE}:test" ${DOCKER_DIR}

# args:
#   ${DOCKER_IMAGE}
#   ${DOCKER_TAG}
.publish_dockerhub:
  image: "adorsys/ci-build"
  script:
    - docker tag "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE}:test" "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_TAG}"

    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_TAG}"
    - docker logout

# args:
#   ${DOCKER_IMAGE}
#   ${DOCKER_TAG}
#   $(OPENSHIFT_NAMESPACE)
.deploy_openshift:
  image: "adorsys/ci-build"
  script:
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_TAG}"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/${DOCKER_IMAGE}:latest"
