---
language: java

jdk:
  - openjdk8

git:
  submodules: false

cache:
  directories:
    - $HOME/.m2

# Schritte um Build-Dependencies herunterladen
before_install:
  - mvn --version

install:
  - mvn -DskipTests -Dmaven.javadoc.skip=true -B -V -U install

# Schritte um Build zu bauen
before_script:
  - mvn --version

script:
  - mvn -B -V clean install
  - mvn -B -V javadoc:javadoc
  - mvn -B -V pmd:check
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=adorsys_XS2A-Sandbox

addons:
  sonarcloud:
    organization: "adorsys"
    token:
      secure: $SONARCLOUD_TOKEN
