version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:
  xs2a-fakesmtp-data:
  xs2a-ledgers-data:
  xs2a-tpp-rest-server-data:

services:
  # Xs2a connector example
  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples:5.10
    container_name: xs2a-connector-examples
    restart: on-failure
    ports:
      - "8089:8089"
      - "8189:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=mock-qwac
      - ASPSP-PROFILE_BASEURL=http://xs2a-aspsp-profile:8080/api/v1
      - CONSENT-SERVICE_BASEURL=http://xs2a-consent-management:8080/api/v1
      - CMS_URL=http://xs2a-consent-management:8080
      - LEDGERS_URL=http://ledgers:8088
      - QWAC_CERTIFICATE_MOCK=-----BEGIN CERTIFICATE-----MIIFNjCCAx6gAwIBAgIEcQJvYzANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJERTEQMA4GA1UECAwHQkFWQVJJQTESMBAGA1UEBwwJTnVyZW1iZXJnMSIwIAYDVQQKDBlUcnVzdCBTZXJ2aWNlIFByb3ZpZGVyIEFHMR8wHQYDVQQLDBZJbmZvcm1hdGlvbiBUZWNobm9sb2d5MB4XDTIwMDMwNDA5MTYxM1oXDTIxMDMwNDAwMDAwMFowgcExITAfBgNVBAoMGEZpY3Rpb25hbCBDb3Jwb3JhdGlvbiBBRzElMCMGCgmSJomT8ixkARkWFXB1YmxpYy5jb3Jwb3JhdGlvbi5kZTEfMB0GA1UECwwWSW5mb3JtYXRpb24gVGVjaG5vbG9neTEQMA4GA1UEBhMHR2VybWFueTEPMA0GA1UECAwGQmF5ZXJuMRIwEAYDVQQHDAlOdXJlbWJlcmcxHTAbBgNVBGEMFFBTRERFLUZBS0VOQ0EtODdCMkFDMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApLM+4noVMsJVHmdYpeLfAoT6ASyVedSTnhDc+uO9ZHBCW9CX2WdkL1M2ObG/qLJcI0kCiHE4wMmllgT+6Vec3Uce398406yGNLh95N9bEKjx+lIs7iM1KEmsrX2RjciStigMPu8nrTyZi8w8rlC7lCT0wQ63+u7W/Sr9guBUZCBmxWiWDOf4fQOsKhK0RvrP7Q4FeTsQEGdmwkQzQIzk0sNyDrVUqqs5qLqQJESTjQ1u9b2zQe0f14PPiNVFUIy0m/vxXl1O5pPiUlT8N+IAi9cHqUQxBdBtkvaAT6uFRJAPevGGtmQ66iEhl1pCfK5RpxnsS5GwS7vz81PYApPFIQIDAQABo34wfDB6BggrBgEFBQcBAwRuMGwGBgQAgZgnAjBiMDkwEQYHBACBmCcBAwwGUFNQX0FJMBEGBwQAgZgnAQIMBlBTUF9QSTARBgcEAIGYJwEEDAZQU1BfSUMMGVRydXN0IFNlcnZpY2UgUHJvdmlkZXIgQUcMCkRFLUZBS0VOQ0EwDQYJKoZIhvcNAQELBQADggIBABnAZg21fFw7qZ4ksOqj6l/Su61WmHSIxiDyoVQx3I1uaf4CM7vPn7anCduxCLmbyrqDgzV6gF00QkTZLhPeHbRf9g39wlxoOoOkuuIeo+Tq+xoIqJ7Nh+dDX4NJgbmNRlLFfpzftAQks+Xu9He+uze6twXMYYVLmPSJsfa1+aYYh1LroiXc/wcGVQeQ9mNmWR93ok4xryjKK0G1RfDM2gyRl36wBMDAf8SVCfEXlvwsMMC4Iue+CIlGXxgU7hKslRR3CPOpdi/nmXvuI+O8NXnOS4A3x8iM9erwOQgJ7g75p+kP/tMmWxU0LVKWqsQY+xBtp/UJ6LKXSS0ipK+Wc3OtIm+NSsFAo9oWwMI9wYRoyWzkfiklNLadBBJLN0RHuira87B0nNwWo7H3QomVuDkpwO2rfOgKlI+HltMYNSIUhMBxyGg18GoXZC3si0bNZx/NQFNM6oQjRVVgmnE81inc6g3KY7K/QQqYQW0d4vtR2LYEYqDYh0yiLhEDY+ztuEMa4OqgXpnmWx4Z8SE8WSRZwnBzBs6klJVDhg3SzfdX4wDh1SA3AqBx8Rl/FKkAdB/2gpMRHuTHHYJTPnJGwQOTWFO2I6raCY+yojcLpex2eIFJGJfP9IP9TulXYKzjCMBXLbUCRx+drTxd+1YAwv2rWrEyki2C5AqZQNKyXdMo-----END CERTIFICATE-----
    volumes:
      - ./bank-profile/qwac.properties:/opt/gateway-app/qwac.properties
    networks:
      - xs2a-net
    depends_on:
      - xs2a-aspsp-profile
      #- xs2a-consent-management
      #- ledgers

  # Xs2a aspsp profile
  xs2a-aspsp-profile:
    image: adorsys/xs2a-aspsp-profile:5.10
    container_name: xs2a-aspsp-profile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx256M"
      - SPRING_PROFILES_ACTIVE=debug_mode
      - BANK_PROFILE_PATH=bank_profile_ledgers.yml
    volumes:
      - ./bank-profile/bank_profile_ledgers.yml:/opt/profile/bank_profile_ledgers.yml
    ports:
      - "48080:8080"
    networks:
      - xs2a-net

  # Consent management
  xs2a-consent-management:
    image: adorsys/xs2a-consent-management:5.10
    container_name: xs2a-consent-management
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
      - ASPSP-PROFILE_BASEURL=http://xs2a-aspsp-profile:8080/api/v1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - SERVER_KEY=secret123
      - SPRING_LIQUIBASE_ENABLED=true
      - USED-NON-RECURRING-CONSENT-EXPIRATION.CRON.EXPRESSION=0 0 * * * *
    depends_on:
      - xs2a-consent-management-db

  # Xs2a consent management DB
  xs2a-consent-management-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a-consent-management-db
    restart: on-failure
    volumes:
      - xs2a-connector-data:/var/lib/pgsql/data
      - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms

  # Xs2a online banking backend
  xs2a-online-banking:
    image: adorsys/xs2a-online-banking
    container_name: xs2a-online-banking
    restart: on-failure
    build:
      context: online-banking/online-banking-app
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "8190:8000"
    depends_on:
      - ledgers
      - xs2a-connector-examples
      - xs2a-consent-management-db
    networks:
      - xs2a-net
    environment:
      XS2A_URL: "http://xs2a-connector-examples:8089"
      LEDGERS_URL: "http://ledgers:8088"
      CMS_URL: "http://xs2a-consent-management:8080"
      OBA_URL: "http://localhost:4400"
      SELF_URL: "http://localhost:8090"
      ONLINE_BANKING_SCA_LOGINPAGE: "http://localhost:4400/"
      ONLINE_BANKING_SCA_UIREDIRECT: "true"
      ONLINE-BANKING_URL: "http://xs2a-online-banking:8090/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent"
      SPRING_DATASOURCE_USERNAME: "cms"
      SPRING_DATASOURCE_PASSWORD: "cms"
      SERVER_KEY: "secret123"

  # Ledgers
  ledgers:
    image: adorsys/ledgers:2.9
    container_name: ledgers
    restart: on-failure
    networks:
      - xs2a-net
    ports:
      - "8088:8088"
      - "8188:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,sandbox
      - SPRING_JPA_SHOW_SQL=false
      - DB_HOST=xs2a-consent-management-db
      - DB_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=ledgers
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms
      - LIQUIBASE_ENABLED=true
      - SCA_MULTILEVEL_ENABLED=false
      - AUTHORISATION_CONFIRMATION_ENABLED=false
      - SPRING_MAIL_HOST=fakesmtp
      - SPRING_MAIL_PORT=25
    volumes:
      - xs2a-ledgers-data:/var/lib/data
    depends_on:
      - fakesmtp

  # Xs2a online banking frontend
  xs2a-online-banking-ui:
    image: adorsys/xs2a-online-banking-ui
    restart: on-failure
    build:
      context: oba-ui
      dockerfile: Dockerfile
    ports:
      - "4400:4400"
    networks:
      - xs2a-net
    environment:
      ONLINE_BANKING_SERVER_URL: "http://xs2a-online-banking:8090"
      DEV_PORTAL_URL_EXT: "http://localhost:4206"
    depends_on:
      - xs2a-online-banking
      - developer-portal-ui

  # TPP-UI
  xs2a-tpp-ui:
    image: adorsys/xs2a-bank-tpp-ui
    restart: on-failure
    environment:
      - TPP_REST_SERVER_URL=http://xs2a-tpp-rest-server:8093
      - CERT_GEN_URL=http://certificate-generator:8092
      - CERT_GEN_ENABLED=true
    build:
      context: tpp-ui
      dockerfile: Dockerfile
    ports:
      - "4205:4205"
    networks:
      - xs2a-net
    depends_on:
      - certificate-generator
      - xs2a-tpp-rest-server

  # TPP-REST-SERVER
  xs2a-tpp-rest-server:
    image: adorsys/xs2a-tpp-rest-server
    restart: on-failure
    environment:
      LEDGERS_URL: "http://ledgers:8088"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent"
      SPRING_DATASOURCE_USERNAME: "cms"
      SPRING_DATASOURCE_PASSWORD: "cms"
    build:
      context: tpp-app/tpp-rest-server
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
      - "5005:5005"
    networks:
      - xs2a-net
    depends_on:
      - ledgers
      - xs2a-consent-management-db
    volumes:
      - xs2a-tpp-rest-server-data:/var/lib/data

  # Developer portal ui
  developer-portal-ui:
    image: adorsys/xs2a-bank-devportal
    restart: on-failure
    build:
      context: developer-portal-ui
      dockerfile: Dockerfile
    ports:
      - "4206:4206"
    networks:
      - xs2a-net
    depends_on:
      - xs2a-connector-examples
    environment:
      - XS2A_URL=http://xs2a-connector-examples:8089
      - ASPSP_URL=http://xs2a-aspsp-profile:8080
      - ENVLINK_DEVELOPER_PORTAL=https://dev-dynamicsandbox-developerportalui.cloud.adorsys.de/
      - ENVLINK_XS2A_INTERFACE_SWAGGER=https://dev-dynamicsandbox-xs2a.cloud.adorsys.de/
      - ENVLINK_CONSENT_MANAGEMENT_SYSTEM=https://dev-dynamicsandbox-cms.cloud.adorsys.de
      - ENVLINK_LEDGERS=https://dev-dynamicsandbox-ledgers.cloud.adorsys.de
      - ENVLINK_ASPSP_PROFILE_SWAGGER=https://dev-dynamicsandbox-aspspprofile.cloud.adorsys.de
      - ENVLINK_TPP_UI=https://blub-dynamicsandbox-tppui.cloud.adorsys.de/login
      - ENVLINK_ONLINE_BANKING_UI=https://dev-dynamicsandbox-onlinebankingui.cloud.adorsys.de/account-information/login
      - ENVLINK_ONLINE_BANKING_BACKEND=https://dev-dynamicsandbox-onlinebanking.cloud.adorsys.de/swagger-ui.html
      - ENVLINK_CERTIFICATE_GENERATOR=https://dev-dynamicsandbox-certificategenerator.cloud.adorsys.de/swagger-ui.html

  # Certificate generator
  certificate-generator:
    image: adorsys/xs2a-certificate-generator
    restart: on-failure
    build:
      context: certificate-generator
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    networks:
      - xs2a-net

  # Fake SMTP
  fakesmtp:
    image: munkyboy/fakesmtp:latest
    networks:
      - xs2a-net
    volumes:
      - xs2a-fakesmtp-data:/var/mail
