version: "3"

services:

  # Postman test
  postman_tests:
    image: xs2a_postman_tests
    build:
      context: .
    command:
      run postman_collection.json
      -g postman_global_variable.json
      -e postman_environment_local.json
      -r cli,html
      --reporter-html-template html_report_template.hbs
      --reporter-html-export postman-tests-report.html
    networks:
      - xs2a-net
    volumes:
      - ./:/etc/newman
